myext.lo: /home/qinkaizhu/soft/lnmp/src/php-5.4.34/ext/myext/myext.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/qinkaizhu/soft/lnmp/src/php-5.4.34/ext/myext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/qinkaizhu/soft/lnmp/src/php-5.4.34/ext/myext/myext.c -o myext.lo 
$(phplibdir)/myext.la: ./myext.la
	$(LIBTOOL) --mode=install cp ./myext.la $(phplibdir)

./myext.la: $(shared_objects_myext) $(MYEXT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_myext) $(MYEXT_SHARED_LIBADD)

